# Generated by Django 4.0.2 on 2022-02-14 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=140)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('date', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peeps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chirp', to='peep.peep')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chirp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
