# Generated by Django 4.0.2 on 2022-02-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peep',
            old_name='username',
            new_name='owner',
        ),
    ]
