# Generated by Django 4.0.2 on 2022-02-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peep', '0002_rename_username_peep_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peep',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
